test:
  hearing-test: digit-in-noise
  start_snr: 5
  correct_threshold: 2
  minimum_threshold: -40
  incorrect_threshold: 1
  step_size: [5, 3, 1]
  reversal_limit: 10
  stimuli_type: digits
  noise:
    type: babble #[white, babble]
    src: "/Users/user/Documents/Projects/PhD/Wordnet-Hearing-Test/audio_processing/noise/babble.wav"

response_capturing: asr #[cli, asr]
stimuli_vocalizer:
  name: tts #[tts, recorded]
  src: "media/digit_recordings/22k"

ml:
  asr_type: SpeechBrain #[SpeechBrain, SimpleASR]
  asr_source: "speechbrain/asr-wav2vec2-commonvoice-en" #["speechbrain/asr-wav2vec2-commonvoice-en","speechbrain/asr-crdnn-rnnlm-librispeech"]
  asr_save_dir: "models/asr/asr-wav2vec2-commonvoice-en" #["models/asr/asr-wav2vec2-commonvoice-en","models/asr/asr-crdnn-rnnlm-librispeech"]
