test:
  hearing-test: digit-in-noise
  start-snr: 5
  correct_threshold: 2
  incorrect_threshold: 1
  step_size: [5, 3, 1]
  reversal_limit: 10
  stimuli_type: digits
  noise: white-noise

ml:
  asr: ARLibrispeech
